### ISSUE TITLE
Could you release this on the Chrome web store? :)

### ISSUE THREAD

**Issue by vergenzt** [helmus/Jira-Hot-Linker#1]
I spent a good amount of time looking for this exact feature and can't wait to try it out.

**Comment by helmus** [comment]
Wooot, a user, this is great ! I will publish it over the weekend. In the mean while, take a look here for installation instructions:
https://github.com/helmus/Jira-Hot-Linker/blob/master/README.md

It's actually very easy to do !

**Comment by vergenzt** [comment]
I went through those and installed it, it'd just be nice to not have to do that, haha.

**Comment by helmus** [comment]
Wonderfull! Let me now if you have any feedback. I've been planning to add some additional features, like comments, extra fields, options for domains etc...

**Comment by helmus** [comment]
https://chrome.google.com/webstore/detail/jira-hotlinker/lbifpcpomdegljfpfhgfcjdabbeallhk?authuser=1
