### ISSUE TITLE
Requests to JIRA REST API does not return data

### ISSUE THREAD

**Issue by kaspars-ozols** [helmus/Jira-Hot-Linker#11]
Requests are made to correct API and they return data, but Chrome Extension is not able to access it because it gets blocked by CORB.

![image](https://user-images.githubusercontent.com/6103815/55324321-5c2a3200-548a-11e9-8dc9-c6e846eb99e5.png)

As a result, extension fails to work in latest versions of Chrome.

Google Chrome is up to date
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by helmus** [comment]
Sorry for the delay on this @kaspars-ozols  ! This should have been addressed with 1.6.0, now available on chrome store !
