### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Tukks** [helmus/Jira-Hot-Linker#17]
Do you plan to add a firefox support on your extension?

This is the last extension I need to make the switch from Chrome to Firefox

Thank's for this amazing extension, it save me a lot of click daily

**Comment by helmus** [comment]
So I assume I can close https://github.com/helmus/Jira-Hot-Linker/issues/16 ? 😅

**Comment by helmus** [comment]
Thanks for being a user Tukks, I am not planning on migrating to firefox anytime soon, the change for that would be quite substantial. But if you want to submit a PR, we can definitely include it !

**Comment by pweiss-mri** [comment]
I don't expect this to change your mind but I'd love a Firefox version as well.
