### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by GreenGremlin** [helmus/Jira-Hot-Linker#22]
The hot-linker popup can be a bit jaring when Github is in dark mode. It would be nice to have the option to configure Jira Hot-linker for dark mode.

**Comment by karolVimn** [comment]
+1

**Comment by helmus** [comment]
Pr has been merged, I will release this to chrome store this week.

**Comment by helmus** [comment]
This has been released to chrome store:
https://chrome.google.com/webstore/detail/jira-hotlinker/lbifpcpomdegljfpfhgfcjdabbeallhk?hl=en
