### ISSUE TITLE
Optional configurable GitHub base URL for Github Enterprise support

### ISSUE THREAD

**Issue by richellis** [helmus/Jira-Hot-Linker#3]
Could you add a configuration option to set the GitHub base URL to allow GitHub Enterprise support?

For example, `https://github.mycompany.com`

Looks like this URL pattern would need to be added to `jira-plugin/manifest.json`, not sure if that can be parameterized or updated dynamically somehow?

**Comment by helmus** [comment]
Hello, Thank you for opening the issue ! 
I'll try to do this over the weekend.

Best,
Willem

**Comment by obohaciak** [comment]
+1

Same here. This would be very much appreaciated with our GitHub Enterprise setup as well!

**Comment by helmus** [comment]
Fixed with release https://github.com/helmus/Jira-Hot-Linker/releases/tag/1.4 ! 
Let me know if you run into any issues configuring the new domains !

**Comment by obohaciak** [comment]
Cool, thanks! Already trying it out.
