### ISSUE TITLE
Support filtered list of Jira projects

### ISSUE THREAD

**Issue by obohaciak** [helmus/Jira-Hot-Linker#4]
Hi helmus,

I got the 1.4.0 release from Chrome Web Store and tried it with my GitHub Enterprise instance, however I'm getting:

> Uncaught (in promise) {message: "QUOTA_BYTES_PER_ITEM quota exceeded"}, mainAsyncLocal, content.jsx:170

Just guessing I might have too many projects - the API call to return the projects from my Jira returns several thousand projects. Perhaps this could be the reason? 

In any case, this many projects will not do much good to performance. Perhaps another option to filter only the projects I'm interested in by their key(s)?

Thanks!

**Comment by helmus** [comment]
I see, I released a fix for this in 1.4.1 just now. However, if you are having thousands of projects, you might see some performance degradation during mouse move. 
I will add a project filter option in the next release hopefully this weekend.

**Comment by obohaciak** [comment]
Thanks helmus! I'm on 1.4.1 now and I can confirm all is working just right.
