### ISSUE TITLE
Highlight/emphasize Jira issue reference

### ISSUE THREAD

**Issue by obohaciak** [helmus/Jira-Hot-Linker#5]
Hi helmus,
Would you consider a small enhancement? 
Right now the Jira issue references do not stand out readily from the surrounding text which is most typically a commit message. It would be great if the references were turned into hyperlinks or at least were emphasized in some way to make them more prominent. 
I understand that it's hard to say where the reference is going to appear and what kind of element one hovers over, but I think a generally safe to assume it's always text. I can imagine a change in font weight, color or add an underline if not a full hypelink... However, it does change how the Jira issue lookup works though. I understand that right now the Jira server is polled only when hovering over an element. What I'm suggesting would mean emphasizing any references as soon as they appear on the page.
What do you think?

**Comment by helmus** [comment]
I think I understand your request but I want to better understand the problem you are trying to solve. 
The goal of the plugin is to make sure the user does not have to go to the jira site, but instead bring jira to github ( or any other site ), this is to minimize context switching. 

So I am thinking you want a way to faster get to the ticket on the jira site, so instead I would ask, what is it that you can not do with the current plugin that requires you go to the jira site ?

**Comment by obohaciak** [comment]
Thanks for the quick reply! I appreciate that you're investing your time to better understand the request.

To be more accurate, it's not necessary for me to navigate to Jira. The plugin has the necessary info and also contains a link already if needed. What I'd like is to have references to Jira issues more noticable on GitHub. Currently, they're rendered the same way as the rest of the commit message and so they blend in. 

For example, I'd like this

> [Fixed] Added Nicolas Cage and his awesome hair
> 
> **APP-1234** Add a lot more Nicolas Cage to the app

Instead of 

> [Fixed] Added Nicolas Cage and his awesome hair
> 
> APP-1234 Add a lot more Nicolas Cage to the app

(Not necessarily bold, just some way of emphasis)

**Comment by helmus** [comment]
Hmm, this is possible but a little tricky because it not only requires scanning of the entire page, but also continuous monitoring after that, github is a very dynamic site and sub sections are reloaded all the time. I'm also a little worried about side effects of mutating the dom that could interact with proper functionality of the site. 

To further better understand your use case, do you have pull requests that have several tickets in the commits and you want to consult all the tickets ? 
One functionality I have been considering is adding a list of the other tickets on the page in the same pop up, so you can discover and consult other tickets on the page quickly.

**Comment by obohaciak** [comment]
Yes, we often have pull requests that lump multiple Jira issues together. It would be nice if there was a summary list.

However my primary use case was to really be able to spot the references to Jira issues immediately. To make them stand out from the rest of the text.

**Comment by helmus** [comment]
I feel partial about interfering with the dom page. interfering with a web page is brittle and breaks in unexpected ways. 
However I do like the idea of a summary, I'm thinking about adding a keyboard shortcut that would open the tooltip with the first found ticket on the page and arrow functions to navigate between other tickets on the page.

If you feel strongly about having the tickets them self light up, I'm happy to take a look at a pr and include it as an optional feature.

**Comment by obohaciak** [comment]
Alright, please keep the issue open for the time being and I'll see what I can do.
