### ISSUE TITLE
False Positive tooltips

### ISSUE THREAD

**Issue by ecsmba15** [helmus/Jira-Hot-Linker#6]
I get popup tooltips in cases that I should not get them. for example:
create new ticket -> issue type selector

http://dropcanvas.com/#1eGU2uPHqn9wDc

**Comment by helmus** [comment]
Thank you for reporting this bug, this should be fixed with release [1.5.3](https://github.com/helmus/Jira-Hot-Linker/releases/tag/1.5.3)
