### ISSUE TITLE
Tooltip in jira not safe

### ISSUE THREAD

**Issue by tjhiggins** [helmus/Jira-Hot-Linker#7]
<img width="271" alt="screen shot 2018-07-31 at 1 06 00 pm" src="https://user-images.githubusercontent.com/737712/43475066-936be9e4-94c2-11e8-8d4d-274892b48654.png">

**Comment by helmus** [comment]
Hello, I'm not sure what you are pointing out here, could you be a little bit more specific please ?

**Comment by tjhiggins** [comment]
Oh sorry was just pointing out that the html was escaped. `<span class="count">1</span> pull request` instead of `1 pull request`. Doesn't really matter unless you add project labels :). Should have just combined the issues...

**Comment by helmus** [comment]
This is a tooltip in jira and not related to jira hot linker. Closing
