### ISSUE TITLE
Feature Request: Add pull request labels to tooltip in Jira

### ISSUE THREAD

**Issue by tjhiggins** [helmus/Jira-Hot-Linker#8]
<img width="271" alt="screen shot 2018-07-31 at 1 06 00 pm" src="https://user-images.githubusercontent.com/737712/43475156-d70d780c-94c2-11e8-9ff9-e88ec1c523d9.png">

We use pull request labels to designate pull requests that have been approved. Would help me a lot to have them show in Jira.

**Comment by helmus** [comment]
Hmmm, this actually makes a lot of sense. I will see what I can do if I can find some time !

**Comment by helmus** [comment]
@tjhiggins
